# Generated by Django 2.2.7 on 2019-11-16 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Product')),
                ('category', models.CharField(choices=[('other', 'Other'), ('food', 'Food'), ('clothes', 'Clothes'), ('household', 'Home items')], default='other', max_length=50, verbose_name='Category')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Description')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='product_images', verbose_name='Photo')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(max_length=2000, verbose_name='Feedback')),
                ('point', models.IntegerField(verbose_name='Point')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='reporter.Product', verbose_name='Product')),
            ],
        ),
    ]
